"use server";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { requireAdmin, hashPassword } from "@/lib/auth";
import { audit, db, users } from "@/lib/domain";
import { trilinkrEmail, passwordSchema } from "@/lib/validation";
import { z } from "zod";
const optionalDate = z.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD.").or(z.literal("")).transform((value) => value || null);
const optionalSalary = z.string().trim().regex(/^\d+$/, "Use a whole number of rupees.").or(z.literal("")).transform((value) => value ? Number(value) : null).refine((value) => value === null || value >= 0, "Salary cannot be negative.");
const profileSchema = z.object({ name: z.string().trim().min(2).max(100), email: trilinkrEmail, phone: z.string().trim().max(30).or(z.literal("")).transform((value) => value || null), dateOfBirth: optionalDate, monthlySalary: optionalSalary, dateOfJoining: optionalDate });
function profileValues(formData: FormData) { return { name: formData.get("name"), email: formData.get("email"), phone: formData.get("phone"), dateOfBirth: formData.get("dateOfBirth"), monthlySalary: formData.get("monthlySalary"), dateOfJoining: formData.get("dateOfJoining") }; }
export async function createUser(formData: FormData) { const admin = await requireAdmin(); const parsed = z.object({ ...profileSchema.shape, role: z.enum(["ADMIN", "MEMBER"]), password: passwordSchema }).safeParse({ ...profileValues(formData), role: formData.get("role"), password: formData.get("password") }); if (!parsed.success) throw new Error("Invalid user details"); const existing = (await db.select({ id: users.id }).from(users).where(eq(users.email, parsed.data.email)).limit(1))[0]; if (existing) throw new Error("Email already exists"); const user = (await db.insert(users).values({ name: parsed.data.name, email: parsed.data.email, phone: parsed.data.phone, dateOfBirth: parsed.data.dateOfBirth, monthlySalary: parsed.data.monthlySalary, dateOfJoining: parsed.data.dateOfJoining, role: parsed.data.role, passwordHash: await hashPassword(parsed.data.password), forcePasswordChange: true }).returning())[0]; await audit(admin.id, "USER_CREATED", "USER", user.id, { role: user.role }); revalidatePath("/team"); }
export async function updateUserProfile(_previousState: { ok: boolean; message: string }, formData: FormData) { const admin = await requireAdmin(); const id = String(formData.get("id")); const parsed = profileSchema.safeParse(profileValues(formData)); if (!parsed.success) return { ok: false, message: "Please check the details and try again." }; const target = (await db.select({ id: users.id, email: users.email }).from(users).where(eq(users.id, id)).limit(1))[0]; if (!target) return { ok: false, message: "User not found." }; const duplicate = (await db.select({ id: users.id }).from(users).where(eq(users.email, parsed.data.email)).limit(1))[0]; if (duplicate && duplicate.id !== id) return { ok: false, message: "Email already exists." }; await db.update(users).set({ ...parsed.data, updatedAt: new Date() }).where(eq(users.id, id)); await audit(admin.id, "USER_PROFILE_UPDATED", "USER", id, { emailChanged: target.email !== parsed.data.email, fields: ["name", "email", "phone", "dateOfBirth", "monthlySalary", "dateOfJoining"] }); revalidatePath("/team"); return { ok: true, message: "Details saved." }; }
export async function toggleUser(formData: FormData) { const admin = await requireAdmin(); const id = String(formData.get("id")); if (id === admin.id) throw new Error("You cannot deactivate your own account."); const target = (await db.select().from(users).where(eq(users.id, id)).limit(1))[0]; if (!target) throw new Error("User not found"); await db.update(users).set({ active: !target.active, deactivatedAt: target.active ? new Date() : null, updatedAt: new Date() }).where(eq(users.id, id)); await audit(admin.id, target.active ? "USER_DEACTIVATED" : "USER_REACTIVATED", "USER", id); revalidatePath("/team"); }
export async function changeRole(formData: FormData) { const admin = await requireAdmin(); const id = String(formData.get("id")); if (id === admin.id) throw new Error("You cannot change your own role."); const role = formData.get("role"); if (role !== "ADMIN" && role !== "MEMBER") throw new Error("Invalid role"); const target = (await db.select().from(users).where(eq(users.id, id)).limit(1))[0]; if (!target) throw new Error("User not found"); await db.update(users).set({ role, updatedAt: new Date() }).where(eq(users.id, id)); await audit(admin.id, "USER_ROLE_CHANGED", "USER", id, { from: target.role, to: role }); revalidatePath("/team"); }
