"use server";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { requireAdmin, hashPassword } from "@/lib/auth";
import { audit, db, users } from "@/lib/domain";
import { trilinkrEmail, passwordSchema } from "@/lib/validation";
import { z } from "zod";
export async function createUser(formData: FormData) { const admin = await requireAdmin(); const parsed = z.object({ name: z.string().trim().min(2).max(100), email: trilinkrEmail, role: z.enum(["ADMIN", "MEMBER"]), password: passwordSchema }).safeParse({ name: formData.get("name"), email: formData.get("email"), role: formData.get("role"), password: formData.get("password") }); if (!parsed.success) throw new Error("Invalid user details"); const existing = (await db.select({ id: users.id }).from(users).where(eq(users.email, parsed.data.email)).limit(1))[0]; if (existing) throw new Error("Email already exists"); const user = (await db.insert(users).values({ name: parsed.data.name, email: parsed.data.email, role: parsed.data.role, passwordHash: await hashPassword(parsed.data.password), forcePasswordChange: true }).returning())[0]; await audit(admin.id, "USER_CREATED", "USER", user.id, { role: user.role }); revalidatePath("/team"); }
export async function toggleUser(formData: FormData) { const admin = await requireAdmin(); const id = String(formData.get("id")); if (id === admin.id) throw new Error("You cannot deactivate your own account."); const target = (await db.select().from(users).where(eq(users.id, id)).limit(1))[0]; if (!target) throw new Error("User not found"); await db.update(users).set({ active: !target.active, deactivatedAt: target.active ? new Date() : null, updatedAt: new Date() }).where(eq(users.id, id)); await audit(admin.id, target.active ? "USER_DEACTIVATED" : "USER_REACTIVATED", "USER", id); revalidatePath("/team"); }
export async function changeRole(formData: FormData) { const admin = await requireAdmin(); const id = String(formData.get("id")); if (id === admin.id) throw new Error("You cannot change your own role."); const role = formData.get("role"); if (role !== "ADMIN" && role !== "MEMBER") throw new Error("Invalid role"); const target = (await db.select().from(users).where(eq(users.id, id)).limit(1))[0]; if (!target) throw new Error("User not found"); await db.update(users).set({ role, updatedAt: new Date() }).where(eq(users.id, id)); await audit(admin.id, "USER_ROLE_CHANGED", "USER", id, { from: target.role, to: role }); revalidatePath("/team"); }
