"use server";
import { and, eq, max } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { audit, db, getOrCreateBoard, kanbanColumns, tasks } from "@/lib/domain";
import { z } from "zod";
const name = z.string().trim().min(1).max(80);
export async function addColumn(formData: FormData) { const user = await requireUser(); const board = await getOrCreateBoard(user.id); const title = name.parse(formData.get("title")); const position = Number((await db.select({ value: max(kanbanColumns.position) }).from(kanbanColumns).where(eq(kanbanColumns.boardId, board.id)))[0]?.value ?? -1) + 1; const column = (await db.insert(kanbanColumns).values({ boardId: board.id, title, position }).returning())[0]; await audit(user.id, "COLUMN_CREATED", "KANBAN_COLUMN", column.id); revalidatePath("/board"); revalidatePath("/board/settings"); }
export async function renameColumn(formData: FormData) { const user = await requireUser(); const board = await getOrCreateBoard(user.id); const id = String(formData.get("id")); const title = name.parse(formData.get("title")); const column = (await db.select().from(kanbanColumns).where(and(eq(kanbanColumns.id, id), eq(kanbanColumns.boardId, board.id))).limit(1))[0]; if (!column) throw new Error("Column not found"); await db.update(kanbanColumns).set({ title, updatedAt: new Date() }).where(eq(kanbanColumns.id, id)); await audit(user.id, "COLUMN_RENAMED", "KANBAN_COLUMN", id); revalidatePath("/board"); revalidatePath("/board/settings"); }
export async function deleteColumn(formData: FormData) { const user = await requireUser(); const board = await getOrCreateBoard(user.id); const id = String(formData.get("id")); const column = (await db.select().from(kanbanColumns).where(and(eq(kanbanColumns.id, id), eq(kanbanColumns.boardId, board.id))).limit(1))[0]; if (!column) throw new Error("Column not found"); const hasTasks = (await db.select({ id: tasks.id }).from(tasks).where(eq(tasks.columnId, id)).limit(1))[0]; if (hasTasks) throw new Error("Move all tasks before deleting this column"); await db.delete(kanbanColumns).where(eq(kanbanColumns.id, id)); await audit(user.id, "COLUMN_DELETED", "KANBAN_COLUMN", id); revalidatePath("/board"); revalidatePath("/board/settings"); }
