"use server";
import { and, eq, max } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { activity, audit, db, taskSubtasks, taskComments, tasks, users } from "@/lib/domain";

const taskEditInput = z.object({ taskId: z.string().uuid(), title: z.string().trim().min(1).max(160), description: z.string().trim().max(5000), priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]), dueDate: z.string().optional(), assignedToUserId: z.string().uuid() });
const subtaskInput = z.object({ taskId: z.string().uuid(), title: z.string().trim().min(1).max(300) });
const titleInput = z.object({ taskId: z.string().uuid(), title: z.string().trim().min(1).max(160) });

async function editableTask(taskId: string) {
  const user = await requireUser();
  const task = (await db.select().from(tasks).where(eq(tasks.id, taskId)).limit(1))[0];
  if (!task || (task.assignedToUserId !== user.id && task.createdByUserId !== user.id && user.role !== "ADMIN")) throw new Error("Forbidden");
  return { user, task };
}

export async function addComment(formData: FormData) { const { user } = await editableTask(String(formData.get("taskId"))); const taskId = String(formData.get("taskId")); const body = String(formData.get("body") ?? "").trim(); if (!body || body.length > 5000) throw new Error("Comment is required"); await db.insert(taskComments).values({ taskId, userId: user.id, body }); await activity(taskId, user.id, "COMMENT_ADDED"); await audit(user.id, "TASK_COMMENT_ADDED", "TASK", taskId); revalidatePath(`/tasks/${taskId}`); }

export async function addSubtask(formData: FormData) { const parsed = subtaskInput.safeParse({ taskId: formData.get("taskId"), title: formData.get("title") }); if (!parsed.success) throw new Error("Invalid subtask details"); const { user } = await editableTask(parsed.data.taskId); const order = (await db.select({ value: max(taskSubtasks.position) }).from(taskSubtasks).where(eq(taskSubtasks.taskId, parsed.data.taskId)))[0]?.value; const subtask = (await db.insert(taskSubtasks).values({ taskId: parsed.data.taskId, title: parsed.data.title, position: Number(order ?? -1) + 1, createdByUserId: user.id }).returning())[0]; await activity(parsed.data.taskId, user.id, "SUBTASK_ADDED", { subtaskId: subtask.id, title: subtask.title }); await audit(user.id, "TASK_SUBTASK_ADDED", "TASK_SUBTASK", subtask.id, { taskId: parsed.data.taskId }); revalidatePath(`/tasks/${parsed.data.taskId}`); }

export async function toggleSubtask(formData: FormData) { const taskId = String(formData.get("taskId")); const subtaskId = String(formData.get("subtaskId")); const { user } = await editableTask(taskId); const subtask = (await db.select().from(taskSubtasks).where(and(eq(taskSubtasks.id, subtaskId), eq(taskSubtasks.taskId, taskId))).limit(1))[0]; if (!subtask) throw new Error("Subtask not found"); const completed = String(formData.get("completed")) === "true"; await db.update(taskSubtasks).set({ completedAt: completed ? new Date() : null, completedByUserId: completed ? user.id : null, updatedAt: new Date() }).where(eq(taskSubtasks.id, subtaskId)); await activity(taskId, user.id, completed ? "SUBTASK_COMPLETED" : "SUBTASK_REOPENED", { subtaskId, title: subtask.title }); await audit(user.id, completed ? "TASK_SUBTASK_COMPLETED" : "TASK_SUBTASK_REOPENED", "TASK_SUBTASK", subtaskId, { taskId }); revalidatePath(`/tasks/${taskId}`); revalidatePath("/board"); }

export async function updateTask(formData: FormData) { const parsed = taskEditInput.safeParse({ taskId: formData.get("taskId"), title: formData.get("title"), description: formData.get("description") ?? "", priority: formData.get("priority"), dueDate: formData.get("dueDate") || undefined, assignedToUserId: formData.get("assignedToUserId") }); if (!parsed.success) throw new Error("Invalid task details"); const { user, task } = await editableTask(parsed.data.taskId); const assignee = (await db.select({ id: users.id }).from(users).where(and(eq(users.id, parsed.data.assignedToUserId), eq(users.active, true))).limit(1))[0]; if (!assignee) throw new Error("Active assignee not found"); const nextDueDate = parsed.data.dueDate ? new Date(`${parsed.data.dueDate}T23:59:59Z`) : null; const changes: Record<string, { from: string | null; to: string | null }> = {}; if (task.title !== parsed.data.title) changes.title = { from: task.title, to: parsed.data.title }; if ((task.description ?? "") !== parsed.data.description) changes.description = { from: task.description, to: parsed.data.description || null }; if (task.priority !== parsed.data.priority) changes.priority = { from: task.priority, to: parsed.data.priority }; if (task.assignedToUserId !== parsed.data.assignedToUserId) changes.assignee = { from: task.assignedToUserId, to: parsed.data.assignedToUserId }; if ((task.dueDate?.toISOString().slice(0, 10) ?? null) !== (parsed.data.dueDate ?? null)) changes.dueDate = { from: task.dueDate?.toISOString().slice(0, 10) ?? null, to: parsed.data.dueDate ?? null }; if (!Object.keys(changes).length) { revalidatePath(`/tasks/${task.id}`); return; } await db.update(tasks).set({ title: parsed.data.title, description: parsed.data.description || null, priority: parsed.data.priority, dueDate: nextDueDate, assignedToUserId: parsed.data.assignedToUserId, updatedAt: new Date() }).where(eq(tasks.id, task.id)); await activity(task.id, user.id, "TASK_UPDATED", { changes }); await audit(user.id, "TASK_UPDATED", "TASK", task.id, { changes }); revalidatePath(`/tasks/${task.id}`); revalidatePath("/board"); revalidatePath("/dashboard"); }
export async function updateTaskTitle(formData: FormData) { const parsed = titleInput.safeParse({ taskId: formData.get("taskId"), title: formData.get("title") }); if (!parsed.success) throw new Error("Invalid task title"); const { user, task } = await editableTask(parsed.data.taskId); if (task.title === parsed.data.title) { revalidatePath(`/tasks/${task.id}`); return; } await db.update(tasks).set({ title: parsed.data.title, updatedAt: new Date() }).where(eq(tasks.id, task.id)); const changes = { title: { from: task.title, to: parsed.data.title } }; await activity(task.id, user.id, "TASK_UPDATED", { changes }); await audit(user.id, "TASK_TITLE_UPDATED", "TASK", task.id, { changes }); revalidatePath(`/tasks/${task.id}`); revalidatePath("/board"); revalidatePath("/dashboard"); }
