import { pgEnum, pgTable, text, timestamp, uuid, boolean, integer, jsonb, index, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const roleEnum = pgEnum("role", ["ADMIN", "MEMBER"]);
export const priorityEnum = pgEnum("priority", ["LOW", "MEDIUM", "HIGH", "URGENT"]);

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), email: text("email").notNull(), passwordHash: text("password_hash").notNull(), role: roleEnum("role").default("MEMBER").notNull(), active: boolean("active").default(true).notNull(), forcePasswordChange: boolean("force_password_change").default(true).notNull(), deactivatedAt: timestamp("deactivated_at", { withTimezone: true }), ...timestamps,
}, (t) => [uniqueIndex("users_email_idx").on(t.email)]);

export const sessions = pgTable("sessions", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), tokenHash: text("token_hash").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("sessions_token_idx").on(t.tokenHash), index("sessions_user_idx").on(t.userId)]);
export const kanbanBoards = pgTable("kanban_boards", { id: uuid("id").defaultRandom().primaryKey(), ownerUserId: uuid("owner_user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), name: text("name").notNull(), ...timestamps }, (t) => [index("boards_owner_idx").on(t.ownerUserId), uniqueIndex("boards_owner_unique_idx").on(t.ownerUserId)]);
export const kanbanColumns = pgTable("kanban_columns", { id: uuid("id").defaultRandom().primaryKey(), boardId: uuid("board_id").references(() => kanbanBoards.id, { onDelete: "cascade" }).notNull(), title: text("title").notNull(), position: integer("position").notNull(), ...timestamps }, (t) => [index("columns_board_idx").on(t.boardId)]);
export const tasks = pgTable("tasks", { id: uuid("id").defaultRandom().primaryKey(), title: text("title").notNull(), description: text("description"), boardId: uuid("board_id").references(() => kanbanBoards.id, { onDelete: "cascade" }).notNull(), columnId: uuid("column_id").references(() => kanbanColumns.id, { onDelete: "restrict" }).notNull(), createdByUserId: uuid("created_by_user_id").references(() => users.id, { onDelete: "restrict" }).notNull(), assignedToUserId: uuid("assigned_to_user_id").references(() => users.id, { onDelete: "restrict" }).notNull(), priority: priorityEnum("priority").default("MEDIUM").notNull(), dueDate: timestamp("due_date", { withTimezone: true }), position: integer("position").notNull(), completedAt: timestamp("completed_at", { withTimezone: true }), ...timestamps }, (t) => [index("tasks_assignee_idx").on(t.assignedToUserId), index("tasks_board_idx").on(t.boardId), index("tasks_column_idx").on(t.columnId), index("tasks_due_idx").on(t.dueDate)]);
export const taskComments = pgTable("task_comments", { id: uuid("id").defaultRandom().primaryKey(), taskId: uuid("task_id").references(() => tasks.id, { onDelete: "cascade" }).notNull(), userId: uuid("user_id").references(() => users.id, { onDelete: "restrict" }).notNull(), body: text("body").notNull(), ...timestamps });
export const taskActivities = pgTable("task_activities", { id: uuid("id").defaultRandom().primaryKey(), taskId: uuid("task_id").references(() => tasks.id, { onDelete: "cascade" }).notNull(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), action: text("action").notNull(), metadata: jsonb("metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("task_activities_task_idx").on(t.taskId, t.createdAt)]);
export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), recipientUserId: uuid("recipient_user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), type: text("type").notNull(), title: text("title").notNull(), message: text("message").notNull(), readAt: timestamp("read_at", { withTimezone: true }), relatedTaskId: uuid("related_task_id").references(() => tasks.id, { onDelete: "set null" }), relatedAttendanceSessionId: uuid("related_attendance_session_id"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("notifications_recipient_read_idx").on(t.recipientUserId, t.readAt)]);
export const attendanceSessions = pgTable("attendance_sessions", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "restrict" }).notNull(), checkInAt: timestamp("check_in_at", { withTimezone: true }).notNull(), checkOutAt: timestamp("check_out_at", { withTimezone: true }), correctedByUserId: uuid("corrected_by_user_id").references(() => users.id, { onDelete: "set null" }), correctionReason: text("correction_reason"), ...timestamps }, (t) => [index("attendance_user_date_idx").on(t.userId, t.checkInAt), uniqueIndex("attendance_one_open_session_idx").on(t.userId).where(sql`${t.checkOutAt} is null`)]);
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id"), metadata: jsonb("metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("audit_entity_date_idx").on(t.entityType, t.entityId, t.createdAt)]);
