import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Bell, CalendarOff, ClipboardCheck, LayoutDashboard, ListTodo, LogOut, ShieldCheck, Users } from "lucide-react";
import { destroySession, getCurrentUser } from "@/lib/auth";
import { initials } from "@/lib/utils";

export default async function WorkspaceLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const user = await getCurrentUser();
  if (!user) return null;
  if (user.forcePasswordChange) redirect("/change-password");
  const nav = [{ href: "/dashboard", label: "Dashboard", icon: LayoutDashboard }, { href: "/board", label: "My Board", icon: ListTodo }, { href: "/tasks", label: "My Tasks", icon: ListTodo }, { href: "/attendance", label: "Attendance", icon: ClipboardCheck }, ...(user.role === "ADMIN" ? [{ href: "/team", label: "Team", icon: Users }, { href: "/team-attendance", label: "Team Attendance", icon: ShieldCheck }, { href: "/leave", label: "Leave Management", icon: CalendarOff }, { href: "/audit", label: "Audit Logs", icon: ShieldCheck }] : [])];
  return <div className="flex min-h-screen"><aside className="hidden w-60 shrink-0 border-r border-line bg-white px-4 py-6 md:block"><Link href="/dashboard" aria-label="Go to TriLinkr dashboard" className="mb-10 block px-2"><span className="block h-10 w-36 overflow-hidden rounded-lg bg-[#fffaf7] transition hover:opacity-85"><Image src="/trilinkr-logo.png" alt="TriLinkr" width={180} height={72} className="h-full w-full object-cover object-center mix-blend-multiply" /></span></Link><nav className="space-y-1">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted hover:bg-canvas hover:text-ink"><Icon size={17} />{label}</Link>)}</nav></aside><div className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b border-line bg-white px-5 md:px-8"><Link href="/dashboard" aria-label="Go to TriLinkr dashboard" className="block h-8 w-28 overflow-hidden rounded-md bg-[#fffaf7] md:hidden"><Image src="/trilinkr-logo.png" alt="TriLinkr" width={180} height={72} className="h-full w-full object-cover object-center mix-blend-multiply" /></Link><div className="ml-auto flex items-center gap-4"><Link href="/notifications" aria-label="Notifications" className="text-muted hover:text-ink"><Bell size={19} /></Link><div className="flex items-center gap-2 border-l border-line pl-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-accent text-xs font-bold text-brand">{initials(user.name)}</span><span className="hidden text-sm font-medium sm:block">{user.name}</span><form action={async () => { "use server"; await destroySession(); redirect("/login"); }}><button aria-label="Sign out" className="ml-2 text-muted hover:text-ink"><LogOut size={16} /></button></form></div></div></header><main className="mx-auto max-w-[1400px] p-5 md:p-8">{children}</main></div></div>;
}
