"use client";
import { useState } from "react";
import { DndContext, type DragEndEvent, useDraggable, useDroppable } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import Link from "next/link";
import { MoreHorizontal, Plus } from "lucide-react";
import { Badge } from "@/components/ui";
type Column = { id: string; title: string }; type Task = { id: string; title: string; priority: string; assignee: string; columnId: string };
function Card({ task }: { task: Task }) { const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: task.id }); return <article ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform) }} {...listeners} {...attributes} className={`rounded-xl border border-line bg-white p-4 shadow-sm ${isDragging ? "opacity-60" : ""}`}><Link href={`/tasks/${task.id}`} onClick={(event) => { if (isDragging) event.preventDefault(); }} className="block"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-medium leading-5">{task.title}</h3><MoreHorizontal size={15} className="shrink-0 text-muted" /></div><div className="mt-4 flex items-center justify-between"><Badge tone={task.priority === "URGENT" ? "red" : task.priority === "HIGH" ? "amber" : "neutral"}>{task.priority}</Badge><span className="text-xs text-muted">{task.assignee}</span></div></Link></article>; }
function ColumnView({ column, tasks }: { column: Column; tasks: Task[] }) { const { isOver, setNodeRef } = useDroppable({ id: column.id }); return <div ref={setNodeRef} className={`min-w-[260px] rounded-2xl bg-[#f5eee8] p-3 transition ${isOver ? "ring-2 ring-brand" : ""}`}><div className="flex items-center justify-between px-2 py-2"><div className="flex items-center gap-2"><h2 className="text-sm font-semibold">{column.title}</h2><span className="text-xs text-muted">{tasks.length}</span></div><MoreHorizontal size={17} className="text-muted" /></div><div className="space-y-3 pt-2">{tasks.map((task) => <Card key={task.id} task={task} />)}</div><Link href="/board/new" className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg py-2 text-sm text-muted hover:bg-white"><Plus size={15} /> Add task</Link></div>; }
export function BoardClient({ columns, initialTasks }: { columns: Column[]; initialTasks: Task[] }) { const [tasks, setTasks] = useState(initialTasks); const [error, setError] = useState<string | null>(null); async function onDragEnd(event: DragEndEvent) { const taskId = String(event.active.id); const columnId = event.over?.id ? String(event.over.id) : null; if (!columnId || !columns.some((column) => column.id === columnId)) return; const previous = tasks; setError(null); setTasks(tasks.map((task) => task.id === taskId ? { ...task, columnId } : task)); const response = await fetch("/api/tasks/move", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ taskId, columnId }) }); if (!response.ok) { setTasks(previous); setError("That move could not be saved. The board was restored."); } } return <><DndContext onDragEnd={onDragEnd}><div className="grid min-h-[560px] gap-4 overflow-x-auto pb-4 md:grid-cols-2 xl:grid-cols-4">{columns.map((column) => <ColumnView key={column.id} column={column} tasks={tasks.filter((task) => task.columnId === column.id)} />)}</div></DndContext>{error && <p role="alert" className="mt-3 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}</>; }
