"use client";

import { useRef } from "react";
import { Info, Pencil, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui";
import { deleteGroupRoom, updateGroupName } from "@/app/(workspace)/chat/actions";

type Member = { id: string; name: string; email: string };

export function ChatRoomHeader({ room, members, canRename, canDelete }: { room: { id: string; name: string; type: "TEAM" | "PRIVATE" | "GROUP"; createdByUserId: string | null }; members: Member[]; canRename: boolean; canDelete: boolean }) {
  const dialogRef = useRef<HTMLDialogElement>(null);

  return <><div className="flex items-center justify-between border-b border-line px-5 py-4"><button type="button" onClick={() => dialogRef.current?.showModal()} className="group text-left" aria-label={`View details for ${room.name}`}><h2 className="flex items-center gap-2 font-semibold group-hover:text-brand">{room.name}{canRename && <Pencil size={14} className="text-brand" />}</h2><p className="mt-1 text-xs text-muted">{room.type === "TEAM" ? "Everyone in TriLinkr" : room.type === "GROUP" ? `${members.length} members · Private group conversation` : "Private conversation"}</p></button><button type="button" onClick={() => dialogRef.current?.showModal()} className="rounded-lg p-2 text-muted hover:bg-canvas hover:text-brand" aria-label="View conversation details"><Info size={18} /></button></div><dialog ref={dialogRef} className="w-[min(520px,calc(100vw-2rem))] rounded-2xl border border-line bg-canvas p-0 text-ink shadow-2xl backdrop:bg-ink/40"><div className="flex items-center justify-between border-b border-line bg-white px-6 py-4"><div><p className="text-sm text-brand">Conversation details</p><h2 className="mt-1 text-xl font-semibold">{room.name}</h2></div><button type="button" aria-label="Close conversation details" onClick={() => dialogRef.current?.close()} className="rounded-lg p-2 text-muted hover:bg-canvas hover:text-ink"><X size={18} /></button></div><div className="space-y-5 p-6"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted">Members</p><div className="mt-2 space-y-2">{members.map((member) => <div key={member.id} className="rounded-lg border border-line bg-white px-3 py-2"><p className="text-sm font-semibold">{member.name}</p><p className="text-xs text-muted">{member.email}</p></div>)}</div></div>{canRename && <form action={updateGroupName} className="flex items-end gap-2 border-t border-line pt-5"><input type="hidden" name="roomId" value={room.id} /><label className="flex-1 text-sm font-medium">Edit group name<input name="name" required minLength={2} maxLength={80} defaultValue={room.name} className="mt-1 w-full rounded-lg border border-line bg-white px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-accent" /></label><Button type="submit" className="bg-white !text-ink ring-1 ring-line hover:bg-canvas"><Pencil size={15} className="mr-2" /> Save</Button></form>}{canDelete && <form action={deleteGroupRoom} className="border-t border-line pt-5"><input type="hidden" name="roomId" value={room.id} /><Button type="submit" className="bg-red-600 hover:bg-red-700"><Trash2 size={15} className="mr-2" /> Delete group</Button><p className="mt-2 text-xs text-muted">Deleting a group removes its messages and membership.</p></form>}</div></dialog></>;
}
