"use client";

import { useRef } from "react";
import { Plus, X } from "lucide-react";
import { Button, Input } from "@/components/ui";
import { createLead } from "@/app/(workspace)/leads/actions";

export function LeadCreateModal({ type }: { type: "EMPLOYER" | "CONSULTANT" }) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const label = type === "EMPLOYER" ? "Employer" : "Consultant";
  return <><Button type="button" onClick={() => dialogRef.current?.showModal()}><Plus size={17} className="mr-2" /> Create lead</Button><dialog ref={dialogRef} className="w-[min(680px,calc(100vw-2rem))] rounded-2xl border border-line bg-canvas p-0 text-ink shadow-2xl backdrop:bg-ink/40"><div className="flex items-center justify-between border-b border-line bg-white px-6 py-4"><div><p className="text-sm text-brand">New {label} lead</p><h2 className="mt-1 text-xl font-semibold">Create lead</h2></div><button type="button" aria-label="Close create lead form" onClick={() => dialogRef.current?.close()} className="rounded-lg p-2 text-muted hover:bg-canvas hover:text-ink"><X size={18} /></button></div><form action={createLead} className="grid gap-4 p-6 md:grid-cols-2"><input type="hidden" name="type" value={type} /><label className="text-sm font-medium">Company name<Input name="companyName" required placeholder="Company or organisation" /></label><label className="text-sm font-medium">Contact person name<Input name="contactName" required placeholder="Full name" /></label><label className="text-sm font-medium">Phone number<Input name="phone" required placeholder="Phone number" /></label><label className="text-sm font-medium">Email ID<Input name="email" type="email" placeholder="name@company.com" /></label><label className="text-sm font-medium">LinkedIn ID / URL<Input name="linkedinUrl" type="url" placeholder="https://linkedin.com/in/..." /></label><label className="text-sm font-medium">Lead status<select name="status" defaultValue="NEW" className="mt-1 w-full rounded-lg border border-line bg-white px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-accent"><option value="NEW">New</option><option value="INTRO_SENT">Intro Sent</option><option value="FOLLOW_UP">Follow up</option><option value="WHATSAPP">WhatsApp</option><option value="ONBOARDED">Onboarded</option><option value="DROPPED">Dropped</option></select></label><label className="text-sm font-medium md:col-span-2">Initial follow-up / comments<textarea name="comments" rows={4} placeholder="Add context or the first follow-up note..." className="mt-1 w-full rounded-lg border border-line bg-white px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-accent" /></label><div className="flex justify-end gap-3 md:col-span-2"><Button type="button" onClick={() => dialogRef.current?.close()} className="bg-white !text-ink ring-1 ring-line hover:bg-canvas">Cancel</Button><Button type="submit">Create lead</Button></div></form></dialog></>;
}
