"use server";
import { and, eq, max } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { activity, audit, db, getOrCreateBoard, kanbanColumns, notify, tasks } from "@/lib/domain";
import { z } from "zod";

const taskInput = z.object({ title: z.string().trim().min(1).max(160), description: z.string().trim().max(5000).optional(), priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]), dueDate: z.string().optional(), assignedToUserId: z.string().uuid() });
export async function createTask(formData: FormData) { const user = await requireUser(); const parsed = taskInput.safeParse({ title: formData.get("title"), description: formData.get("description") || undefined, priority: formData.get("priority"), dueDate: formData.get("dueDate") || undefined, assignedToUserId: formData.get("assignedToUserId") }); if (!parsed.success) throw new Error("Invalid task details"); const board = await getOrCreateBoard(parsed.data.assignedToUserId); const first = (await db.select({ id: kanbanColumns.id }).from(kanbanColumns).where(and(eq(kanbanColumns.boardId, board.id), eq(kanbanColumns.position, 0))).limit(1))[0]; if (!first) throw new Error("Board is not configured"); const order = (await db.select({ value: max(tasks.position) }).from(tasks).where(eq(tasks.columnId, first.id)))[0]?.value; const task = (await db.insert(tasks).values({ title: parsed.data.title, description: parsed.data.description, boardId: board.id, columnId: first.id, createdByUserId: user.id, assignedToUserId: parsed.data.assignedToUserId, priority: parsed.data.priority, dueDate: parsed.data.dueDate ? new Date(`${parsed.data.dueDate}T23:59:59Z`) : null, position: Number(order ?? -1) + 1 }).returning())[0]; await activity(task.id, user.id, "CREATED"); await audit(user.id, "TASK_CREATED", "TASK", task.id, { assignedToUserId: task.assignedToUserId }); if (task.assignedToUserId !== user.id) await notify(task.assignedToUserId, "TASK_ASSIGNED", "New task assigned", `${user.name} assigned “${task.title}” to you.`, task.id); revalidatePath("/board"); revalidatePath("/dashboard"); }
export async function moveTask(formData: FormData) { const user = await requireUser(); const taskId = String(formData.get("taskId")); const columnId = String(formData.get("columnId")); const task = (await db.select().from(tasks).where(eq(tasks.id, taskId)).limit(1))[0]; const column = (await db.select().from(kanbanColumns).where(eq(kanbanColumns.id, columnId)).limit(1))[0]; if (!task || !column) throw new Error("Task or column not found"); if (task.assignedToUserId !== user.id && task.createdByUserId !== user.id) throw new Error("Forbidden"); const order = (await db.select({ value: max(tasks.position) }).from(tasks).where(eq(tasks.columnId, columnId)))[0]?.value; await db.update(tasks).set({ columnId, position: Number(order ?? -1) + 1, completedAt: column.title.toLowerCase() === "done" ? new Date() : null, updatedAt: new Date() }).where(eq(tasks.id, taskId)); await activity(taskId, user.id, "STATUS_CHANGED", { columnId }); await audit(user.id, "TASK_MOVED", "TASK", taskId, { columnId }); revalidatePath("/board"); revalidatePath("/dashboard"); }
