import { asc, eq } from "drizzle-orm";
import { requireAdmin } from "@/lib/auth";
import { db, users } from "@/lib/domain";
import { getLeaveCalendar } from "@/lib/leave";
import { formatOrgMonth } from "@/lib/time";
import { saveLeaveOverride } from "./actions";

export default async function LeavePage() {
  await requireAdmin();
  const members = await db.select().from(users).where(eq(users.active, true)).orderBy(asc(users.name));
  const rows = await Promise.all(members.map(async (member) => ({ member, calendar: await getLeaveCalendar(member.id) })));
  return <div className="space-y-6"><div><p className="text-sm text-brand">Administration</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Leave management</h1><p className="mt-2 text-muted">{formatOrgMonth()} · automatic leave applies to completed working days without a check-in.</p></div><section className="rounded-2xl border border-line bg-white p-6 shadow-soft"><h2 className="font-semibold">Monthly summary</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-line bg-canvas text-xs uppercase tracking-wide text-muted"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Present</th><th className="px-4 py-3">On leave</th><th className="px-4 py-3">Pending</th><th className="px-4 py-3">Leave dates</th></tr></thead><tbody>{rows.map(({ member, calendar }) => <tr key={member.id} className="border-b border-line last:border-0"><td className="px-4 py-4 font-medium">{member.name}</td><td className="px-4 py-4">{calendar.presentDays}</td><td className="px-4 py-4 font-semibold text-brand">{calendar.leaveDays}</td><td className="px-4 py-4">{calendar.pendingDays}</td><td className="px-4 py-4 text-xs text-muted">{calendar.days.filter((day) => day.status === "LEAVE").map((day) => `${day.dateKey}${day.overridden ? " *" : ""}`).join(", ") || "—"}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-muted">* indicates an administrator override. Sundays and 1st/3rd/5th Saturdays are off days.</p></section><section className="max-w-2xl rounded-2xl border border-line bg-white p-6 shadow-soft"><h2 className="font-semibold">Override attendance status</h2><p className="mt-1 text-sm text-muted">Use this to mark a team member on leave or present for any date.</p><form action={saveLeaveOverride} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Employee<select name="userId" required className="mt-2 w-full rounded-lg border border-line bg-white px-3 py-2.5 text-sm">{members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label className="text-sm font-medium">Date<input name="leaveDate" type="date" required className="mt-2 w-full rounded-lg border border-line px-3 py-2.5 text-sm" /></label><label className="text-sm font-medium">Status<select name="status" defaultValue="LEAVE" required className="mt-2 w-full rounded-lg border border-line bg-white px-3 py-2.5 text-sm"><option value="LEAVE">On Leave</option><option value="PRESENT">Present</option></select></label><label className="text-sm font-medium">Reason<span className="mt-2 block"><input name="reason" placeholder="Optional reason" className="w-full rounded-lg border border-line px-3 py-2.5 text-sm" /></span></label><button className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Save override</button></form></section></div>;
}
